apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: hotelscom  
spec:
  type: LoadBalancer
  ports:
  - name: "9002"
    port: 9002
    nodePort: 31001    
    targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
