apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: controller
  name: controller
  namespace: hotelscom    
spec:
  type: LoadBalancer
  ports:
  - name: "9101"
    port: 9101
    nodePort: 31101    
    targetPort: 9101
  selector:
    io.kompose.service: controller
status:
  loadBalancer: {}
