kind: PersistentVolume
apiVersion: v1
metadata:
  name: redispv
  labels:
    purpose: redisstorage
  namespace: hotelscom
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/hotels.com/redis"