apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: hotelscom   
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zipkin
    spec:
      containers:
      - image: openzipkin/zipkin:latest
        name: zipkin
        ports:
        - containerPort: 9411
        resources: {}
      restartPolicy: Always
status: {}
