kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-claim0
  name: mysql-claim0
  namespace: hotelscom  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      purpose: mysqlstorage
status: {}