kind: PersistentVolume
apiVersion: v1
metadata:
  name: imagespv
  labels:
    purpose: imagesstorage
  namespace: hotelscom
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/hotels.com/ui/images"