kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysqlpv
  labels:
    purpose: mysqlstorage
  namespace: hotelscom    
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/pv/hotels.com/mysql"