apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
  namespace: hotelscom  
spec:
  type: NodePort
  ports:
  - name: "9001"
    port: 9001
    nodePort: 31000
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
