data:
  .dockercfg: eyJyZWdpc3RyeS5ldS1nYi5ibHVlbWl4Lm5ldCI6eyJ1c2VybmFtZSI6ImFiYWxhc3UxQGluLmlibS5jb20iLCJwYXNzd29yZCI6ImEzcm9zbXRoIiwiZW1haWwiOiJhYmFsYXN1MUBpbi5pYm0uY29tIiwiYXV0aCI6IllXSmhiR0Z6ZFRGQWFXNHVhV0p0TG1OdmJUcGhNM0p2YzIxMGFBPT0ifX0=
kind: Secret
metadata:
  creationTimestamp: 2017-09-12T17:20:54Z
  name: regsecret
  namespace: hotelscom
  resourceVersion: "15437"
  selfLink: /api/v1/namespaces/hotelscom/secrets/regsecret
  uid: bb8a3a90-97de-11e7-a365-c2a85c0547db
type: kubernetes.io/dockercfg