apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dealsquery-service
  name: dealsquery-service
  namespace: hotelscom    
spec:
  type: LoadBalancer
  ports:
  - name: "9013"
    port: 9013
    nodePort: 31013 
    targetPort: 9013
  selector:
    io.kompose.service: dealsquery-service
status:
  loadBalancer: {}
