apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: hotelscom   
spec:
  type: LoadBalancer
  ports:
  - name: "9411"
    port: 9411
    nodePort: 31002    
    targetPort: 9411
  selector:
    io.kompose.service: zipkin
status:
  loadBalancer: {}
