apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
  namespace: hotelscom  
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      imagePullSecrets:
        - name: regsecret    
      containers:
      - env:
        - name: PORT
          value: "9102"
        - name: APIENDPOINTURL
          value: http://9.113.140.160:31101
        imagePullPolicy: IfNotPresent          
        image: {{.Values.image-ui}}
        name: ui
        ports:
        - containerPort: 9102
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/ui/app/images
          name: images-claim0        
      restartPolicy: Always
      volumes:
      - name: images-claim0
        emptyDir: {}    
status: {}
