apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
  namespace: hotelscom   
spec:
  type: LoadBalancer
  ports:
  - name: "9102"
    port: 9102
    nodePort: 31102    
    targetPort: 9102
  selector:
    io.kompose.service: ui
status:
  loadBalancer: {}
